# -*- coding: utf-8 -*-
"""EZ_ROCKPAPERSCI_GAME

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MKBYHJKAaHfssTLYJ7kQkcrol27Mx-bF
"""

import random
print(random.randint(1,10))

"""**randint() function**"""

#(start, end) : Both of them must be integer type values.
#A random integer in range [start, end] including the end points.

arr=['rock','paper','scissor']
arr[2]

P=0
C=0
max=5
arr=['rock','paper','scissor']
while(True):
  i=input("Enter Your Decision:")
  if i not in arr:
    print("!Invalid Input!\n!TRYAGAIN.....!")
  else:
    print("!PROCEED!")
  comp=arr[random.randint(0,2)]
  print("COMPUTER'S DECISION ->",comp)
  print("PLAYER'S DECISION ->",i)
  if(comp==i):
    print("!DRAWWWW!\nPLAYAGAIN.....!")
  else:
      if(comp=='rock' and i=='scissor'):
        print("COMPUTER WINS")
        C=C+1
      elif(comp=='paper' and i=='rock'):
        print("COMPUTER WINS")
        C=C+1
      elif(comp=='scissor' and i=='paper'):
        print("COMPUTER WINS")
        C=C+1
      else:
        print("PLAYER WINS")
        P=P+1
      print("Player's Points: ",P)
      print("Computer's Points: ",C)
  if(P>=max):
    print("!PLAYER WINS!")
    break
  if(C>=max):
    print("!COMPUTER WINS!")
    break